<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite [
  <!ELEMENT suite (test+)>
  <!ATTLIST suite name CDATA #REQUIRED>
  <!ATTLIST suite parallel (methods|tests|classes|instances|none) "none">
  <!ATTLIST suite thread-count CDATA "5">
  
  <!ELEMENT test (parameter*, classes)>
  <!ATTLIST test name CDATA #REQUIRED>
  <!ATTLIST test parallel (methods|tests|classes|instances|none) "none">
  <!ATTLIST test thread-count CDATA "5">
  
  <!ELEMENT parameter EMPTY>
  <!ATTLIST parameter name CDATA #REQUIRED>
  <!ATTLIST parameter value CDATA #REQUIRED>
  
  <!ELEMENT classes (class+)>
  
  <!ELEMENT class EMPTY>
  <!ATTLIST class name CDATA #REQUIRED>
]>
<suite name="Suite" thread-count="5" parallel="tests">
  
  <test thread-count="5" name="chrometest">
   	<parameter name="os" value="Windows" />
  	<parameter name="browser"  value="chrome"/>  
    <classes>
      <class name="TestCases.TC_001_AccountRegistrationTest"/>
    </classes>
  </test> <!-- Test -->
  
  <test thread-count="5" name="edgetest">
   	<parameter name="os" value="Windows" />
  	<parameter name="browser"  value="edge"/>  
    <classes>
      <class name="TestCases.TC_001_AccountRegistrationTest"/>
    </classes>
  </test> <!-- Test -->
  
  
</suite> <!-- Suite -->
